root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./server"
  cmd = "make build-dev"
  delay = 1000
  exclude_dir = [
    ".github",
    "database/migrations",
    "graph/model",
  ]
  exclude_file = [
    "database/*.sql.go", 
    "database/db.go", 
    "database/models.go",
    "graph/generated.go",
  ]
  exclude_regex = [
    "_test.go",
    "graph/_.go"
  ]
  exclude_unchanged = true
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = [
    "go", 
    "sql", 
    "graphql",
  ]
  include_file = [
    "graph/hello.graphql",
    "graph/hello.resolvers.go",
  ]
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
