version: '3.8'
services:
  stadio-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5431:5432'
    volumes: 
      - stadio-db:/var/lib/postgresql/data
volumes:
  stadio-db:
    driver: local