package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.26

import (
	"context"

	"github.com/m3-app/backend/graph/model"
)

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context, name string) (*model.Me, error) {
	return &model.Me{
		Name: name,
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
