//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Addresses struct {
	ID              int64 `sql:"primary_key"`
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Latitude        float64
	Longitude       float64
	MapsLink        string
	FullAddress     string
	LocationAddress int64
}
