//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Country struct {
	Code CountryCodeAlpha2 `sql:"primary_key"`
	Name string
}
