//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Currency struct {
	CurrencyCode string `sql:"primary_key"`
	Name         string
	Symbol       string
	SymbolNative string
	Decimals     int32
	NumToBasic   *int32
}
