//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Event struct {
	ID          int64 `sql:"primary_key"`
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	Description *string
	Type        *string
	StartDate   time.Time
	EndDate     time.Time
	LocationID  *int64
	CreatedByID *int64
	UpdatedByID *int64
}
