//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type GeometryColumns struct {
	FTableCatalog   *string
	FTableSchema    *string
	FTableName      *string
	FGeometryColumn *string
	CoordDimension  *int32
	Srid            *int32
	Type            *string
}
