//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type LocationImage struct {
	ID               int64 `sql:"primary_key"`
	CreatedAt        time.Time
	UpdatedAt        time.Time
	UploadID         string
	OriginalFilename string
	LocationID       int64
	Default          bool
	Caption          *string
	CreatedBy        *int64
	UpdatedBy        *int64
	ContentType      string
}
