//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Review struct {
	ID            int64 `sql:"primary_key"`
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Rating        float64
	Message       *string
	LocationID    *int64
	EventID       int64
	ParticipantID int64
}
