//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type WeekDay string

const (
	WeekDay_Sunday    WeekDay = "SUNDAY"
	WeekDay_Monday    WeekDay = "MONDAY"
	WeekDay_Tuesday   WeekDay = "TUESDAY"
	WeekDay_Wednesday WeekDay = "WEDNESDAY"
	WeekDay_Thursday  WeekDay = "THURSDAY"
	WeekDay_Friday    WeekDay = "FRIDAY"
	WeekDay_Saturday  WeekDay = "SATURDAY"
)

func (e *WeekDay) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "SUNDAY":
		*e = WeekDay_Sunday
	case "MONDAY":
		*e = WeekDay_Monday
	case "TUESDAY":
		*e = WeekDay_Tuesday
	case "WEDNESDAY":
		*e = WeekDay_Wednesday
	case "THURSDAY":
		*e = WeekDay_Thursday
	case "FRIDAY":
		*e = WeekDay_Friday
	case "SATURDAY":
		*e = WeekDay_Saturday
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for WeekDay enum")
	}

	return nil
}

func (e WeekDay) String() string {
	return string(e)
}
