// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gmodel

import (
	"time"
)

type Auth struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Query struct {
}

type User struct {
	ID          int64      `json:"id" sql:"primary_key"`
	CreatedAt   time.Time  `json:"createdAt"`
	UpdatedAt   time.Time  `json:"updatedAt"`
	Email       string     `json:"email"`
	PhoneNumber *string    `json:"phoneNumber,omitempty"`
	Name        string     `json:"name"`
	Avatar      *string    `json:"avatar,omitempty"`
	BirthDate   *time.Time `json:"birthDate,omitempty"`
	Bio         *string    `json:"bio,omitempty"`
	Active      *bool      `json:"active,omitempty"`
}
