// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Message struct {
	Message string `json:"message"`
}

type UserInput struct {
	Email     string  `json:"email"`
	Name      string  `json:"name"`
	AvatarURL *string `json:"avatarUrl"`
}
