// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/m3-app/backend/ent"
)

type AuthState struct {
	User  *ent.User `json:"user"`
	Token string    `json:"token"`
}

type Message struct {
	Message string `json:"message"`
}

type UserInput struct {
	Email     string  `json:"email"`
	Name      string  `json:"name"`
	AvatarURL *string `json:"avatarUrl"`
}
