CREATE TABLE "currency" (
    "currency_code" VARCHAR(3) NOT NULL UNIQUE PRIMARY KEY,
    "name" VARCHAR(100) NOT NULL,
    "symbol" VARCHAR(10) NOT NULL,
    "symbol_native" VARCHAR(10) NOT NULL,
    "decimals" INTEGER NOT NULL,
    "num_to_basic" INTEGER
);
-- Source: https://raw.githubusercontent.com/ourworldincode/currency/main/currencies.json
INSERT INTO "currency" (
    "currency_code",
    "name",
    "symbol",
    "symbol_native",
    "decimals",
    "num_to_basic"
) VALUES ('AED', 'United Arab Emirates Dirham', 'د.إ.', 'د.إ.', 2, 100), ('AFN', 'Afghan Afghani', 'Af', '؋', 2, 100), ('ALL', 'Albanian Lek', 'L', 'L', 2, 100), ('AMD', 'Armenian Dram', '֏', 'դր', 2, 100), ('ANG', 'Netherlands Antillean Guilder', 'ƒ', 'ƒ', 2, 100), ('AOA', 'Angolan Kwanza', 'Kz', 'Kz', 2, 100), ('ARS', 'Argentine Peso', 'AR$', '$', 2, 100), ('AUD', 'Australian Dollar', 'AU$', '$', 2, 100), ('AWG', 'Aruban Florin', 'ƒ', 'ƒ', 2, 100), ('AZN', 'Azerbaijani Manat', 'ман', '₼', 2, 100), ('BAM', 'Bosnia and Herzegovina Convertible Mark', 'KM', 'КМ', 2, 100), ('BBD', 'Barbadian Dollar', 'BBD$', '$', 2, 100), ('BDT', 'Bangladeshi Taka', '৳', '৳', 2, 100), ('BGN', 'Bulgarian Lev', 'лв.', 'лв.', 2, 100), ('BHD', 'Bahraini Dinar', 'BD', 'د.ب.', 3, 1000), ('BIF', 'Burundian Franc', 'FBu', 'FBu', 2, 100), ('BMD', 'Bermudian Dollar', '$', '$', 2, 100), ('BND', 'Brunei Dollar', 'B$', '$', 2, 100), ('BOB', 'Bolivian Boliviano', 'Bs.', 'Bs.', 2, 100), ('BRL', 'Brazilian Real', 'R$', 'R$', 2, 100), ('BSD', 'Bahamian Dollar', '$', '$', 2, 100), ('BTN', 'Bhutanese Ngultrum', 'Nu.', 'Nu.', 2, 100), ('BWP', 'Botswana Pula', 'P', 'P', 2, 100), ('BYN', 'Belarusian Ruble', 'Br', 'руб.', 2, 100), ('BZD', 'Belize Dollar', 'BZ$', '$', 2, 100), ('CAD', 'Canadian Dollar', 'CA$', '$', 2, 100), ('CDF', 'Congolese Franc', 'FC', '₣', 2, 100), ('CHF', 'Swiss Franc', 'Fr.', '₣', 2, 100), ('CKD', 'Cook Islands Dollar', '$', '$', 2, 100), ('CLP', 'Chilean Peso', 'CL$', '$', 0, 100), ('CNY', 'Chinese Yuan', 'CN¥', '¥元', 2, 100), ('COP', 'Colombian Peso', 'CO$', '$', 2, 100), ('CRC', 'Costa Rican Colon', '₡', '₡', 2, 100), ('CUC', 'Cuban convertible Peso', 'CUC$', '$', 2, 100), ('CUP', 'Cuban Peso', '$MN', '₱', 2, 100), ('CVE', 'Cabo Verdean Escudo', 'CV$', '$', 2, 100), ('CZK', 'Czech Koruna', 'Kč', 'Kč', 2, 100), ('DJF', 'Djiboutian Franc', 'Fdj', 'ف.ج.', 2, 100), ('DKK', 'Danish Krone', 'kr.', 'kr.', 2, 100), ('DOP', 'Dominican Peso', 'RD$', '$', 2, 100), ('DZD', 'Algerian Dinar', 'DA', 'د.ج.', 2, 100), ('EGP', 'Egyptian Pound', 'E£', 'ج.م.', 2, 100), ('EHP', 'Sahrawi Peseta', 'Ptas.', 'Ptas.', 2, 100), ('ERN', 'Eritrean Nakfa', 'Nkf', 'ناكفا', 2, 100), ('ETB', 'Ethiopian Birr', 'Br', 'ብር', 2, 100), ('EUR', 'Euro', '€', '€', 2, 100), ('FJD', 'Fijian Dollar', 'FJ$', '$', 2, 100), ('FKP', 'Falkland Islands Pound', 'FK£', '£', 2, 100), ('FOK', 'Faroese Króna', 'kr', 'kr', 2, 100), ('GBP', 'Pound Sterling', '£', '£', 2, 100), ('GEL', 'Georgian Lari', '₾', '₾', 2, 100), ('GGP', 'Guernsey Pound', '£', '£', 2, 100), ('GHS', 'Ghanaian Cedi', 'GH₵', '₵', 2, 100), ('GIP', 'Gibraltar Pound', '£', '£', 2, 100), ('GMD', 'Gambian Dalasi', 'D', 'D', 2, 100), ('GNF', 'Guinean Franc', 'FG', 'FG', 2, 100), ('GTQ', 'Guatemalan Quetzal', 'Q', '$', 2, 100), ('GYD', 'Guyanese Dollar', 'G$', '$', 2, 100), ('HKD', 'Hong Kong Dollar', 'HK$', '$', 2, 100), ('HNL', 'Honduran Lempira', 'L', 'L', 2, 100), ('HRK', 'Croatian Kuna', 'kn', 'kn', 2, 100), ('HTG', 'Haitian Gourde', 'G', 'G', 2, 100), ('HUF', 'Hungarian Forint', 'Ft', 'Ft', 2, 100), ('IDR', 'Indonesian Rupiah', 'Rp', 'Rp', 2, 100), ('ILS', 'Israeli new Shekel', '₪', '₪', 2, 100), ('IMP', 'Manx Pound', '£', '£', 2, 100), ('INR', 'Indian Rupee', 'Rs.', '₹', 2, 100), ('IQD', 'Iraqi Dinar', 'د.ع.', 'د.ع.', 3, 1000), ('IRR', 'Iranian Rial', '﷼', '﷼', 2, 100), ('ISK', 'Icelandic Krona', 'kr', 'kr', 2, 100), ('JEP', 'Jersey Pound', '£', '£', 2, 100), ('JMD', 'Jamaican Dollar', 'J$', '$', 2, 100), ('JOD', 'Jordanian Dinar', 'JD', 'د.أ.', 3, 1000), ('JPY', 'Japanese Yen', '¥', '¥', 2, 100), ('KES', 'Kenyan Shilling', 'KSh', 'KSh', 2, 100), ('KGS', 'Kyrgyzstani Som', 'с', 'с', 2, 100), ('KHR', 'Cambodian Riel', '៛', '៛', 2, 100), ('KID', 'Kiribati Dollar', '$', '$', 2, 100), ('KMF', 'Comorian Franc', 'CF', 'CF', 2, 100), ('KPW', 'North Korean Won', '₩', '₩', 2, 100), ('KRW', 'South Korean Won', '₩', '₩', 2, 100), ('KWD', 'Kuwaiti Dinar', 'KD', 'د.ك.', 3, 1000), ('KYD', 'Cayman Islands Dollar', 'CI$', '$', 2, 100), ('KZT', 'Kazakhstani Tenge', '₸', '₸', 2, 100), ('LAK', 'Lao Kip', '₭N', '₭', 2, 100), ('LBP', 'Lebanese Pound', 'LL.', 'ل.ل.', 2, 100), ('LKR', 'Sri Lankan Rupee', 'Rs.', 'රු or ரூ', 2, 100), ('LRD', 'Liberian Dollar', 'L$', '$', 2, 100), ('LSL', 'Lesotho Loti', 'L', 'L', 2, 100), ('LYD', 'Libyan Dinar', 'LD', 'ل.د.', 3, 1000), ('MAD', 'Moroccan Dirham', 'DH', 'د.م.', 2, 100), ('MDL', 'Moldovan Leu', 'L', 'L', 2, 100), ('MGA', 'Malagasy Ariary', 'Ar', 'Ar', 0, 5), ('MKD', 'Macedonian Denar', 'den', 'ден', 2, 100), ('MMK', 'Myanmar Kyat', 'Ks', 'Ks', 2, 100), ('MNT', 'Mongolian Tögrög', '₮', '₮', 2, 100), ('MOP', 'Macanese Pataca', 'MOP$', 'MOP$', 2, 100), ('MRU', 'Mauritanian Ouguiya', 'UM', 'أ.م.', 0, 5), ('MUR', 'Mauritian Rupee', 'Rs.', 'रु ', 2, 100), ('MVR', 'Maldivian Rufiyaa', 'MRf', '.ރ', 2, 100), ('MWK', 'Malawian Kwacha', 'MK', 'MK', 2, 100), ('MXN', 'Mexican Peso', 'MX$', '$', 2, 100), ('MYR', 'Malaysian Ringgit', 'RM', 'RM', 2, 100), ('MZN', 'Mozambican Metical', 'MTn', 'MT', 2, 100), ('NAD', 'Namibian Dollar', 'N$', '$', 2, 100), ('NGN', 'Nigerian Naira', '₦', '₦', 2, 100), ('NIO', 'Nicaraguan Córdoba', 'C$', 'C$', 2, 100), ('NOK', 'Norwegian Krone', 'kr', 'kr', 2, 100), ('NPR', 'Nepalese Rupee', 'Rs.', 'रू', 2, 100), ('NZD', 'New Zealand Dollar', 'NZ$', '$', 2, 100), ('OMR', 'Omani Rial', 'OR', 'ر.ع.', 3, 1000), ('PAB', 'Panamanian Balboa', 'B/.', 'B/.', 2, 100), ('PEN', 'Peruvian Sol', 'S/.', 'S/.', 2, 100), ('PGK', 'Papua New Guinean Kina', 'K', 'K', 2, 100), ('PHP', 'Philippine Peso', '₱', '₱', 2, 100), ('PKR', 'Pakistani Rupee', 'Rs.', 'Rs', 2, 100), ('PLN', 'Polish Zloty', 'zł', 'zł', 2, 100), ('PND', 'Pitcairn Islands Dollar', '$', '$', 2, 100), ('PRB', 'Transnistrian Ruble', 'р.', 'р.', 2, 100), ('PYG', 'Paraguayan Guaraní', '₲', '₲', 2, 100), ('QAR', 'Qatari Riyal', 'QR', 'ر.ق.', 2, 100), ('RON', 'Romanian Leu', 'L', 'L', 2, 100), ('RSD', 'Serbian Dinar', 'din', 'дин', 2, 100), ('RUB', 'Russian Ruble', '₽', '₽', 2, 100), ('RWF', 'Rwandan Franc', 'FRw', 'R₣', 2, 100), ('SAR', 'Saudi Riyal', 'SR', 'ر.س.', 2, 100), ('SBD', 'Solomon Islands Dollar', 'SI$', '$', 2, 100), ('SCR', 'Seychellois Rupee', 'Rs.', 'Rs', 2, 100), ('SDG', 'Sudanese Pound', '£SD', 'ج.س.', 2, 100), ('SEK', 'Swedish Krona', 'kr', 'kr', 2, 100), ('SGD', 'Singapore Dollar', 'S$', '$', 2, 100), ('SHP', 'Saint Helena Pound', '£', '£', 2, 100), ('SLL', 'Sierra Leonean Leone', 'Le', 'Le', 2, 100), ('SLS', 'Somaliland Shilling', 'Sl', 'Sl', 2, 100), ('SOS', 'Somali Shilling', 'Sh.So.', 'Ssh', 2, 100), ('SRD', 'Surinamese Dollar', 'Sr$', '$', 2, 100), ('SSP', 'South Sudanese Pound', 'SS£', 'SS£', 2, 100), ('STN', 'Sao Tome and Príncipe Dobra', 'Db', 'Db', 2, 100), ('SVC', 'Salvadoran Colón', '₡', '₡', 2, 100), ('SYP', 'Syrian Pound', 'LS', 'ل.س.', 2, 100), ('SZL', 'Swazi Lilangeni', 'L', 'L', 2, 100), ('THB', 'Thai Baht', '฿', '฿', 2, 100), ('TJS', 'Tajikistani Somoni', 'SM', 'SM', 2, 100), ('TMT', 'Turkmenistan Manat', 'm.', 'T', 2, 100), ('TND', 'Tunisian Dinar', 'DT', 'د.ت.', 3, 1000), ('TOP', 'Tongan Paʻanga', 'T$', 'PT', 2, 100), ('TRY', 'Turkish Lira', 'TL', '₺', 2, 100), ('TTD', 'Trinidad and Tobago Dollar', 'TT$', '$', 2, 100), ('TVD', 'Tuvaluan Dollar', '$', '$', 2, 100), ('TWD', 'New Taiwan Dollar', 'NT$', '圓', 2, 100), ('TZS', 'Tanzanian Shilling', 'TSh', 'TSh', 2, 100), ('UAH', 'Ukrainian Hryvnia', '₴', 'грн', 2, 100), ('UGX', 'Ugandan Shilling', 'USh', 'Sh', 2, 100), ('USD', 'United States Dollar', '$', '$', 2, 100), ('UYU', 'Uruguayan Peso', '$U', '$', 2, 100), ('UZS', 'Uzbekistani Som', 'сум', 'сум', 2, 100), ('VED', 'Venezuelan bolívar digital', 'Bs.', 'Bs.', 2, 100), ('VEF', 'Venezuelan Bolívar Soberano', 'Bs.F', 'Bs.F', 2, 100), ('VND', 'Vietnamese Dong', '₫', '₫', 2, 10), ('VUV', 'Vanuatu Vatu', 'VT', 'VT', 0, NULL), ('WST', 'Samoan Tala', 'T', 'ST', 2, 100), ('XAF', 'Central African CFA Franc BEAC', 'Fr', 'Fr.', 2, 100), ('XCD', 'East Caribbean Dollar', '$', '$', 2, 100), ('XOF', 'West African CFA Franc BCEAO', '₣', '₣', 2, 100), ('XPF', 'CFP Franc (Franc Pacifique)', '₣', '₣', 0, 100), ('YER', 'Yemeni Rial', 'YR', 'ر.ي.', 2, 100), ('ZAR', 'South African Rand', 'R', 'R', 2, 100), ('ZMW', 'Zambian Kwacha', 'ZK', 'ZK', 2, 100), ('ZWB', 'RTGS Dollar', '', '', 0, NULL), ('ZWL', 'Zimbabwean Dollar', 'Z$', '$', 2, 100);


ALTER TABLE "country"
ADD COLUMN "currency" VARCHAR(3) REFERENCES "currency"("currency_code") ON DELETE SET NULL;
ALTER TABLE "country"
ADD COLUMN "calling_code" VARCHAR(20);
ALTER TABLE "country"
ADD COLUMN "language" VARCHAR(3);
-- Source: https://raw.githubusercontent.com/vijinho/ISO-Country-Data/master/countries.json
UPDATE "country" SET "currency" = 'EUR', "calling_code" = '+376', "language" = 'cat' WHERE "code" = 'AD';
UPDATE "country" SET "currency" = 'AED', "calling_code" = '+971', "language" = 'ara' WHERE "code" = 'AE';
UPDATE "country" SET "currency" = 'AFN', "calling_code" = '+93', "language" = 'pus' WHERE "code" = 'AF';
UPDATE "country" SET "currency" = 'XCD', "calling_code" = '+1 268', "language" = 'eng' WHERE "code" = 'AG';
UPDATE "country" SET "currency" = 'XCD', "calling_code" = '+1 264', "language" = 'eng' WHERE "code" = 'AI';
UPDATE "country" SET "currency" = 'ALL', "calling_code" = '+355', "language" = 'alb' WHERE "code" = 'AL';
UPDATE "country" SET "currency" = 'AMD', "calling_code" = '+374', "language" = 'arm' WHERE "code" = 'AM';
UPDATE "country" SET "currency" = 'AOA', "calling_code" = '+244', "language" = 'por' WHERE "code" = 'AO';
UPDATE "country" SET "currency" = 'ARS', "calling_code" = '+54', "language" = 'spa' WHERE "code" = 'AR';
UPDATE "country" SET "currency" = 'USD', "calling_code" = '+1 684', "language" = 'eng' WHERE "code" = 'AS';
UPDATE "country" SET "currency" = 'EUR', "calling_code" = '+43', "language" = 'ger' WHERE "code" = 'AT';
UPDATE "country" SET "currency" = 'AUD', "calling_code" = '+61', "language" = 'eng' WHERE "code" = 'AU';
UPDATE "country" SET "currency" = 'AWG', "calling_code" = '+297', "language" = 'dut' WHERE "code" = 'AW';
UPDATE "country" SET "currency" = 'EUR', "calling_code" = '+358', "language" = 'swe' WHERE "code" = 'AX';
UPDATE "country" SET "currency" = 'AZN', "calling_code" = '+994', "language" = 'aze' WHERE "code" = 'AZ';
UPDATE "country" SET "currency" = 'BAM', "calling_code" = '+387', "language" = 'bos' WHERE "code" = 'BA';
UPDATE "country" SET "currency" = 'BBD', "calling_code" = '+1 246', "language" = 'eng' WHERE "code" = 'BB';
UPDATE "country" SET "currency" = 'BDT', "calling_code" = '+880', "language" = 'ben' WHERE "code" = 'BD';
UPDATE "country" SET "currency" = 'EUR', "calling_code" = '+32', "language" = 'dut' WHERE "code" = 'BE';
UPDATE "country" SET "currency" = 'XOF', "calling_code" = '+226', "language" = 'fre' WHERE "code" = 'BF';
UPDATE "country" SET "currency" = 'BGN', "calling_code" = '+359', "language" = 'bul' WHERE "code" = 'BG';
UPDATE "country" SET "currency" = 'BHD', "calling_code" = '+973', "language" = 'ara' WHERE "code" = 'BH';
UPDATE "country" SET "currency" = 'BIF', "calling_code" = '+257', "language" = 'fre' WHERE "code" = 'BI';
UPDATE "country" SET "currency" = 'XOF', "calling_code" = '+229', "language" = 'fre' WHERE "code" = 'BJ';
UPDATE "country" SET "currency" = 'EUR', "calling_code" = '+590', "language" = 'fre' WHERE "code" = 'BL';
UPDATE "country" SET "currency" = 'BMD', "calling_code" = '+1 441', "language" = 'eng' WHERE "code" = 'BM';
UPDATE "country" SET "currency" = 'BND', "calling_code" = '+673', "language" = 'may' WHERE "code" = 'BN';
UPDATE "country" SET "currency" = 'BOB', "calling_code" = '+591', "language" = 'spa' WHERE "code" = 'BO';
UPDATE "country" SET "currency" = 'USD', "calling_code" = '+599', "language" = 'dut' WHERE "code" = 'BQ';
UPDATE "country" SET "currency" = 'BRL', "calling_code" = '+55', "language" = 'por' WHERE "code" = 'BR';
UPDATE "country" SET "currency" = 'BSD', "calling_code" = '+1 242', "language" = 'eng' WHERE "code" = 'BS';
UPDATE "country" SET "currency" = 'INR', "calling_code" = '+975', "language" = 'dzo' WHERE "code" = 'BT';
UPDATE "country" SET "currency" = 'NOK' WHERE "code" = 'BV';
UPDATE "country" SET "currency" = 'BWP', "calling_code" = '+267', "language" = 'eng' WHERE "code" = 'BW';
UPDATE "country" SET "currency" = 'BYN', "calling_code" = '+375', "language" = 'bel' WHERE "code" = 'BY';
UPDATE "country" SET "currency" = 'BZD', "calling_code" = '+501', "language" = 'eng' WHERE "code" = 'BZ';
UPDATE "country" SET "currency" = 'CAD', "calling_code" = '+1', "language" = 'eng' WHERE "code" = 'CA';
UPDATE "country" SET "currency" = 'AUD', "calling_code" = '+61', "language" = 'eng' WHERE "code" = 'CC';
UPDATE "country" SET "currency" = 'CDF', "calling_code" = '+243', "language" = 'fre' WHERE "code" = 'CD';
UPDATE "country" SET "currency" = 'XAF', "calling_code" = '+236', "language" = 'fre' WHERE "code" = 'CF';
UPDATE "country" SET "currency" = 'XAF', "calling_code" = '+242', "language" = 'fre' WHERE "code" = 'CG';
UPDATE "country" SET "currency" = 'CHF', "calling_code" = '+41', "language" = 'ger' WHERE "code" = 'CH';
UPDATE "country" SET "currency" = 'XOF', "calling_code" = '+225', "language" = 'fre' WHERE "code" = 'CI';
UPDATE "country" SET "currency" = 'NZD', "calling_code" = '+682', "language" = 'eng' WHERE "code" = 'CK';
UPDATE "country" SET "currency" = 'CLP', "calling_code" = '+56', "language" = 'spa' WHERE "code" = 'CL';
UPDATE "country" SET "currency" = 'XAF', "calling_code" = '+237', "language" = 'eng' WHERE "code" = 'CM';
UPDATE "country" SET "currency" = 'CNY', "calling_code" = '+86', "language" = 'chi' WHERE "code" = 'CN';
UPDATE "country" SET "currency" = 'COP', "calling_code" = '+57', "language" = 'spa' WHERE "code" = 'CO';
UPDATE "country" SET "currency" = 'CRC', "calling_code" = '+506', "language" = 'spa' WHERE "code" = 'CR';
UPDATE "country" SET "currency" = 'CUP', "calling_code" = '+53', "language" = 'spa' WHERE "code" = 'CU';
UPDATE "country" SET "currency" = 'CVE', "calling_code" = '+238', "language" = 'por' WHERE "code" = 'CV';
UPDATE "country" SET "currency" = 'AUD', "calling_code" = '+61', "language" = 'eng' WHERE "code" = 'CX';
UPDATE "country" SET "currency" = 'EUR', "calling_code" = '+357', "language" = 'gre' WHERE "code" = 'CY';
UPDATE "country" SET "currency" = 'CZK', "calling_code" = '+420', "language" = 'cze' WHERE "code" = 'CZ';
UPDATE "country" SET "currency" = 'EUR', "calling_code" = '+49', "language" = 'ger' WHERE "code" = 'DE';
UPDATE "country" SET "currency" = 'DJF', "calling_code" = '+253', "language" = 'ara' WHERE "code" = 'DJ';
UPDATE "country" SET "currency" = 'DKK', "calling_code" = '+45', "language" = 'dan' WHERE "code" = 'DK';
UPDATE "country" SET "currency" = 'XCD', "calling_code" = '+1 767', "language" = 'eng' WHERE "code" = 'DM';
UPDATE "country" SET "currency" = 'DOP', "calling_code" = '+1 809', "language" = 'spa' WHERE "code" = 'DO';
UPDATE "country" SET "currency" = 'DZD', "calling_code" = '+213', "language" = 'ara' WHERE "code" = 'DZ';
UPDATE "country" SET "currency" = 'USD', "calling_code" = '+593', "language" = 'spa' WHERE "code" = 'EC';
UPDATE "country" SET "currency" = 'EUR', "calling_code" = '+372', "language" = 'est' WHERE "code" = 'EE';
UPDATE "country" SET "currency" = 'EGP', "calling_code" = '+20', "language" = 'ara' WHERE "code" = 'EG';
UPDATE "country" SET "currency" = 'MAD', "calling_code" = '+212' WHERE "code" = 'EH';
UPDATE "country" SET "currency" = 'ERN', "calling_code" = '+291', "language" = 'eng' WHERE "code" = 'ER';
UPDATE "country" SET "currency" = 'EUR', "calling_code" = '+34', "language" = 'spa' WHERE "code" = 'ES';
UPDATE "country" SET "currency" = 'ETB', "calling_code" = '+251', "language" = 'amh' WHERE "code" = 'ET';
UPDATE "country" SET "currency" = 'EUR', "calling_code" = '+358', "language" = 'fin' WHERE "code" = 'FI';
UPDATE "country" SET "currency" = 'FJD', "calling_code" = '+679', "language" = 'eng' WHERE "code" = 'FJ';
UPDATE "country" SET "currency" = 'FKP', "calling_code" = '+500', "language" = 'eng' WHERE "code" = 'FK';
UPDATE "country" SET "currency" = 'USD', "calling_code" = '+691', "language" = 'eng' WHERE "code" = 'FM';
UPDATE "country" SET "currency" = 'DKK', "calling_code" = '+298', "language" = 'fao' WHERE "code" = 'FO';
UPDATE "country" SET "currency" = 'EUR', "calling_code" = '+33', "language" = 'fre' WHERE "code" = 'FR';
UPDATE "country" SET "currency" = 'XAF', "calling_code" = '+241', "language" = 'fre' WHERE "code" = 'GA';
UPDATE "country" SET "currency" = 'GBP', "calling_code" = '+44', "language" = 'eng' WHERE "code" = 'GB';
UPDATE "country" SET "currency" = 'XCD', "calling_code" = '+473', "language" = 'eng' WHERE "code" = 'GD';
UPDATE "country" SET "currency" = 'GEL', "calling_code" = '+995', "language" = 'geo' WHERE "code" = 'GE';
UPDATE "country" SET "currency" = 'EUR', "calling_code" = '+594', "language" = 'fre' WHERE "code" = 'GF';
UPDATE "country" SET "currency" = 'GBP', "calling_code" = '+44', "language" = 'fre' WHERE "code" = 'GG';
UPDATE "country" SET "currency" = 'GHS', "calling_code" = '+233', "language" = 'eng' WHERE "code" = 'GH';
UPDATE "country" SET "currency" = 'GIP', "calling_code" = '+350', "language" = 'eng' WHERE "code" = 'GI';
UPDATE "country" SET "currency" = 'DKK', "calling_code" = '+299', "language" = 'kal' WHERE "code" = 'GL';
UPDATE "country" SET "currency" = 'GMD', "calling_code" = '+220', "language" = 'eng' WHERE "code" = 'GM';
UPDATE "country" SET "currency" = 'GNF', "calling_code" = '+224', "language" = 'fre' WHERE "code" = 'GN';
UPDATE "country" SET "currency" = 'EUR', "calling_code" = '+590', "language" = 'fre' WHERE "code" = 'GP';
UPDATE "country" SET "currency" = 'XAF', "calling_code" = '+240', "language" = 'spa' WHERE "code" = 'GQ';
UPDATE "country" SET "currency" = 'EUR', "calling_code" = '+30', "language" = 'gre' WHERE "code" = 'GR';
UPDATE "country" SET "currency" = 'GBP', "language" = 'eng' WHERE "code" = 'GS';
UPDATE "country" SET "currency" = 'GTQ', "calling_code" = '+502', "language" = 'spa' WHERE "code" = 'GT';
UPDATE "country" SET "currency" = 'USD', "calling_code" = '+1 671', "language" = 'eng' WHERE "code" = 'GU';
UPDATE "country" SET "currency" = 'XOF', "calling_code" = '+245', "language" = 'por' WHERE "code" = 'GW';
UPDATE "country" SET "currency" = 'GYD', "calling_code" = '+592', "language" = 'eng' WHERE "code" = 'GY';
UPDATE "country" SET "currency" = 'HKD', "calling_code" = '+852', "language" = 'chi' WHERE "code" = 'HK';
UPDATE "country" SET "currency" = 'AUD' WHERE "code" = 'HM';
UPDATE "country" SET "currency" = 'HNL', "calling_code" = '+504', "language" = 'spa' WHERE "code" = 'HN';
UPDATE "country" SET "currency" = 'HRK', "calling_code" = '+385', "language" = 'hrv' WHERE "code" = 'HR';
UPDATE "country" SET "currency" = 'HTG', "calling_code" = '+509', "language" = 'fre' WHERE "code" = 'HT';
UPDATE "country" SET "currency" = 'HUF', "calling_code" = '+36', "language" = 'hun' WHERE "code" = 'HU';
UPDATE "country" SET "currency" = 'IDR', "calling_code" = '+62', "language" = 'ind' WHERE "code" = 'ID';
UPDATE "country" SET "currency" = 'EUR', "calling_code" = '+353', "language" = 'eng' WHERE "code" = 'IE';
UPDATE "country" SET "currency" = 'ILS', "calling_code" = '+972', "language" = 'heb' WHERE "code" = 'IL';
UPDATE "country" SET "currency" = 'GBP', "calling_code" = '+44', "language" = 'eng' WHERE "code" = 'IM';
UPDATE "country" SET "currency" = 'INR', "calling_code" = '+91', "language" = 'hin' WHERE "code" = 'IN';
UPDATE "country" SET "currency" = 'USD', "calling_code" = '+246', "language" = 'eng' WHERE "code" = 'IO';
UPDATE "country" SET "currency" = 'IQD', "calling_code" = '+964', "language" = 'ara' WHERE "code" = 'IQ';
UPDATE "country" SET "currency" = 'IRR', "calling_code" = '+98', "language" = 'per' WHERE "code" = 'IR';
UPDATE "country" SET "currency" = 'ISK', "calling_code" = '+354', "language" = 'ice' WHERE "code" = 'IS';
UPDATE "country" SET "currency" = 'EUR', "calling_code" = '+39', "language" = 'ita' WHERE "code" = 'IT';
UPDATE "country" SET "currency" = 'GBP', "calling_code" = '+44', "language" = 'eng' WHERE "code" = 'JE';
UPDATE "country" SET "currency" = 'JMD', "calling_code" = '+1 876', "language" = 'eng' WHERE "code" = 'JM';
UPDATE "country" SET "currency" = 'JOD', "calling_code" = '+962', "language" = 'ara' WHERE "code" = 'JO';
UPDATE "country" SET "currency" = 'JPY', "calling_code" = '+81', "language" = 'jpn' WHERE "code" = 'JP';
UPDATE "country" SET "currency" = 'KES', "calling_code" = '+254', "language" = 'eng' WHERE "code" = 'KE';
UPDATE "country" SET "currency" = 'KGS', "calling_code" = '+996', "language" = 'rus' WHERE "code" = 'KG';
UPDATE "country" SET "currency" = 'KHR', "calling_code" = '+855', "language" = 'khm' WHERE "code" = 'KH';
UPDATE "country" SET "currency" = 'AUD', "calling_code" = '+686', "language" = 'eng' WHERE "code" = 'KI';
UPDATE "country" SET "currency" = 'KMF', "calling_code" = '+269', "language" = 'ara' WHERE "code" = 'KM';
UPDATE "country" SET "currency" = 'XCD', "calling_code" = '+1 869', "language" = 'eng' WHERE "code" = 'KN';
UPDATE "country" SET "currency" = 'KPW', "calling_code" = '+850', "language" = 'kor' WHERE "code" = 'KP';
UPDATE "country" SET "currency" = 'KRW', "calling_code" = '+82', "language" = 'kor' WHERE "code" = 'KR';
UPDATE "country" SET "currency" = 'KWD', "calling_code" = '+965', "language" = 'ara' WHERE "code" = 'KW';
UPDATE "country" SET "currency" = 'KYD', "calling_code" = '+1 345', "language" = 'eng' WHERE "code" = 'KY';
UPDATE "country" SET "currency" = 'KZT', "calling_code" = '+7', "language" = 'kaz' WHERE "code" = 'KZ';
UPDATE "country" SET "currency" = 'LAK', "calling_code" = '+856', "language" = 'lao' WHERE "code" = 'LA';
UPDATE "country" SET "currency" = 'LBP', "calling_code" = '+961', "language" = 'ara' WHERE "code" = 'LB';
UPDATE "country" SET "currency" = 'XCD', "calling_code" = '+1 758', "language" = 'eng' WHERE "code" = 'LC';
UPDATE "country" SET "currency" = 'CHF', "calling_code" = '+423', "language" = 'ger' WHERE "code" = 'LI';
UPDATE "country" SET "currency" = 'LKR', "calling_code" = '+94', "language" = 'sin' WHERE "code" = 'LK';
UPDATE "country" SET "currency" = 'LRD', "calling_code" = '+231', "language" = 'eng' WHERE "code" = 'LR';
UPDATE "country" SET "currency" = 'LSL', "calling_code" = '+266', "language" = 'eng' WHERE "code" = 'LS';
UPDATE "country" SET "currency" = 'EUR', "calling_code" = '+370', "language" = 'lit' WHERE "code" = 'LT';
UPDATE "country" SET "currency" = 'EUR', "calling_code" = '+352', "language" = 'fre' WHERE "code" = 'LU';
UPDATE "country" SET "currency" = 'EUR', "calling_code" = '+371', "language" = 'lav' WHERE "code" = 'LV';
UPDATE "country" SET "currency" = 'LYD', "calling_code" = '+218', "language" = 'ara' WHERE "code" = 'LY';
UPDATE "country" SET "currency" = 'MAD', "calling_code" = '+212', "language" = 'ara' WHERE "code" = 'MA';
UPDATE "country" SET "currency" = 'EUR', "calling_code" = '+377', "language" = 'fre' WHERE "code" = 'MC';
UPDATE "country" SET "currency" = 'MDL', "calling_code" = '+373', "language" = 'rum' WHERE "code" = 'MD';
UPDATE "country" SET "currency" = 'EUR', "calling_code" = '+382', "language" = 'mot' WHERE "code" = 'ME';
UPDATE "country" SET "currency" = 'EUR', "calling_code" = '+590', "language" = 'fre' WHERE "code" = 'MF';
UPDATE "country" SET "currency" = 'MGA', "calling_code" = '+261', "language" = 'fre' WHERE "code" = 'MG';
UPDATE "country" SET "currency" = 'USD', "calling_code" = '+692', "language" = 'eng' WHERE "code" = 'MH';
UPDATE "country" SET "currency" = 'MKD', "calling_code" = '+389', "language" = 'mac' WHERE "code" = 'MK';
UPDATE "country" SET "currency" = 'XOF', "calling_code" = '+223', "language" = 'fre' WHERE "code" = 'ML';
UPDATE "country" SET "currency" = 'MMK', "calling_code" = '+95', "language" = 'bur' WHERE "code" = 'MM';
UPDATE "country" SET "currency" = 'MNT', "calling_code" = '+976', "language" = 'mon' WHERE "code" = 'MN';
UPDATE "country" SET "currency" = 'MOP', "calling_code" = '+853', "language" = 'chi' WHERE "code" = 'MO';
UPDATE "country" SET "currency" = 'USD', "calling_code" = '+1 670', "language" = 'eng' WHERE "code" = 'MP';
UPDATE "country" SET "currency" = 'EUR', "calling_code" = '+596' WHERE "code" = 'MQ';
UPDATE "country" SET "currency" = 'MRU', "calling_code" = '+222', "language" = 'ara' WHERE "code" = 'MR';
UPDATE "country" SET "currency" = 'XCD', "calling_code" = '+1 664' WHERE "code" = 'MS';
UPDATE "country" SET "currency" = 'EUR', "calling_code" = '+356', "language" = 'mlt' WHERE "code" = 'MT';
UPDATE "country" SET "currency" = 'MUR', "calling_code" = '+230', "language" = 'eng' WHERE "code" = 'MU';
UPDATE "country" SET "currency" = 'MVR', "calling_code" = '+960', "language" = 'div' WHERE "code" = 'MV';
UPDATE "country" SET "currency" = 'MWK', "calling_code" = '+265', "language" = 'eng' WHERE "code" = 'MW';
UPDATE "country" SET "currency" = 'MXN', "calling_code" = '+52', "language" = 'spa' WHERE "code" = 'MX';
UPDATE "country" SET "currency" = 'MYR', "calling_code" = '+60', "language" = 'msa' WHERE "code" = 'MY';
UPDATE "country" SET "currency" = 'MZN', "calling_code" = '+258', "language" = 'por' WHERE "code" = 'MZ';
UPDATE "country" SET "currency" = 'NAD', "calling_code" = '+264', "language" = 'eng' WHERE "code" = 'NA';
UPDATE "country" SET "currency" = 'XPF', "calling_code" = '+687', "language" = 'fre' WHERE "code" = 'NC';
UPDATE "country" SET "currency" = 'XOF', "calling_code" = '+227', "language" = 'fre' WHERE "code" = 'NE';
UPDATE "country" SET "currency" = 'AUD', "calling_code" = '+672', "language" = 'eng' WHERE "code" = 'NF';
UPDATE "country" SET "currency" = 'NGN', "calling_code" = '+234', "language" = 'eng' WHERE "code" = 'NG';
UPDATE "country" SET "currency" = 'NIO', "calling_code" = '+505', "language" = 'spa' WHERE "code" = 'NI';
UPDATE "country" SET "currency" = 'EUR', "calling_code" = '+31', "language" = 'dut' WHERE "code" = 'NL';
UPDATE "country" SET "currency" = 'NOK', "calling_code" = '+47', "language" = 'nor' WHERE "code" = 'NO';
UPDATE "country" SET "currency" = 'NPR', "calling_code" = '+977', "language" = 'nep' WHERE "code" = 'NP';
UPDATE "country" SET "currency" = 'AUD', "calling_code" = '+674', "language" = 'eng' WHERE "code" = 'NR';
UPDATE "country" SET "currency" = 'NZD', "calling_code" = '+683', "language" = 'eng' WHERE "code" = 'NU';
UPDATE "country" SET "currency" = 'NZD', "calling_code" = '+64', "language" = 'eng' WHERE "code" = 'NZ';
UPDATE "country" SET "currency" = 'OMR', "calling_code" = '+968', "language" = 'ara' WHERE "code" = 'OM';
UPDATE "country" SET "currency" = 'PAB', "calling_code" = '+507', "language" = 'spa' WHERE "code" = 'PA';
UPDATE "country" SET "currency" = 'PEN', "calling_code" = '+51', "language" = 'spa' WHERE "code" = 'PE';
UPDATE "country" SET "currency" = 'XPF', "calling_code" = '+689', "language" = 'fre' WHERE "code" = 'PF';
UPDATE "country" SET "currency" = 'PGK', "calling_code" = '+675', "language" = 'eng' WHERE "code" = 'PG';
UPDATE "country" SET "currency" = 'PHP', "calling_code" = '+63', "language" = 'eng' WHERE "code" = 'PH';
UPDATE "country" SET "currency" = 'PKR', "calling_code" = '+92', "language" = 'urd' WHERE "code" = 'PK';
UPDATE "country" SET "currency" = 'PLN', "calling_code" = '+48', "language" = 'pol' WHERE "code" = 'PL';
UPDATE "country" SET "currency" = 'EUR', "calling_code" = '+508', "language" = 'eng' WHERE "code" = 'PM';
UPDATE "country" SET "currency" = 'NZD', "calling_code" = '+872', "language" = 'eng' WHERE "code" = 'PN';
UPDATE "country" SET "currency" = 'USD', "calling_code" = '+1 787', "language" = 'spa' WHERE "code" = 'PR';
UPDATE "country" SET "currency" = 'JOD', "calling_code" = '+970', "language" = 'ara' WHERE "code" = 'PS';
UPDATE "country" SET "currency" = 'EUR', "calling_code" = '+351', "language" = 'por' WHERE "code" = 'PT';
UPDATE "country" SET "currency" = 'USD', "calling_code" = '+680', "language" = 'eng' WHERE "code" = 'PW';
UPDATE "country" SET "currency" = 'PYG', "calling_code" = '+595', "language" = 'spa' WHERE "code" = 'PY';
UPDATE "country" SET "currency" = 'QAR', "calling_code" = '+974', "language" = 'ara' WHERE "code" = 'QA';
UPDATE "country" SET "currency" = 'EUR', "calling_code" = '+262', "language" = 'fre' WHERE "code" = 'RE';
UPDATE "country" SET "currency" = 'RON', "calling_code" = '+40', "language" = 'rum' WHERE "code" = 'RO';
UPDATE "country" SET "currency" = 'RSD', "calling_code" = '+381', "language" = 'srp' WHERE "code" = 'RS';
UPDATE "country" SET "currency" = 'RUB', "calling_code" = '+7', "language" = 'rus' WHERE "code" = 'RU';
UPDATE "country" SET "currency" = 'RWF', "calling_code" = '+250', "language" = 'eng' WHERE "code" = 'RW';
UPDATE "country" SET "currency" = 'SAR', "calling_code" = '+966', "language" = 'ara' WHERE "code" = 'SA';
UPDATE "country" SET "currency" = 'SBD', "calling_code" = '+677', "language" = 'eng' WHERE "code" = 'SB';
UPDATE "country" SET "currency" = 'SCR', "calling_code" = '+248', "language" = 'eng' WHERE "code" = 'SC';
UPDATE "country" SET "currency" = 'SDG', "calling_code" = '+249', "language" = 'ara' WHERE "code" = 'SD';
UPDATE "country" SET "currency" = 'SEK', "calling_code" = '+46', "language" = 'swe' WHERE "code" = 'SE';
UPDATE "country" SET "currency" = 'SGD', "calling_code" = '+65', "language" = 'eng' WHERE "code" = 'SG';
UPDATE "country" SET "currency" = 'SHP', "calling_code" = '+290', "language" = 'eng' WHERE "code" = 'SH';
UPDATE "country" SET "currency" = 'EUR', "calling_code" = '+386', "language" = 'slv' WHERE "code" = 'SI';
UPDATE "country" SET "currency" = 'NOK', "calling_code" = '+47' WHERE "code" = 'SJ';
UPDATE "country" SET "currency" = 'EUR', "calling_code" = '+421', "language" = 'slo' WHERE "code" = 'SK';
UPDATE "country" SET "currency" = 'SLL', "calling_code" = '+232', "language" = 'eng' WHERE "code" = 'SL';
UPDATE "country" SET "currency" = 'EUR', "calling_code" = '+378', "language" = 'ita' WHERE "code" = 'SM';
UPDATE "country" SET "currency" = 'XOF', "calling_code" = '+221', "language" = 'fre' WHERE "code" = 'SN';
UPDATE "country" SET "currency" = 'SOS', "calling_code" = '+252', "language" = 'som' WHERE "code" = 'SO';
UPDATE "country" SET "currency" = 'SRD', "calling_code" = '+597', "language" = 'dut' WHERE "code" = 'SR';
UPDATE "country" SET "currency" = 'SSP', "calling_code" = '+211', "language" = 'eng' WHERE "code" = 'SS';
UPDATE "country" SET "currency" = 'STN', "calling_code" = '+239', "language" = 'por' WHERE "code" = 'ST';
UPDATE "country" SET "currency" = 'USD', "calling_code" = '+503', "language" = 'spa' WHERE "code" = 'SV';
UPDATE "country" SET "currency" = 'SYP', "calling_code" = '+963', "language" = 'ara' WHERE "code" = 'SY';
UPDATE "country" SET "currency" = 'SZL', "calling_code" = '+268', "language" = 'eng' WHERE "code" = 'SZ';
UPDATE "country" SET "currency" = 'USD', "calling_code" = '+1 649', "language" = 'eng' WHERE "code" = 'TC';
UPDATE "country" SET "currency" = 'XAF', "calling_code" = '+235', "language" = 'ara' WHERE "code" = 'TD';
UPDATE "country" SET "currency" = 'EUR', "language" = 'fre' WHERE "code" = 'TF';
UPDATE "country" SET "currency" = 'XOF', "calling_code" = '+228', "language" = 'fre' WHERE "code" = 'TG';
UPDATE "country" SET "currency" = 'THB', "calling_code" = '+66', "language" = 'tha' WHERE "code" = 'TH';
UPDATE "country" SET "currency" = 'TJS', "calling_code" = '+992', "language" = 'tgk' WHERE "code" = 'TJ';
UPDATE "country" SET "currency" = 'NZD', "calling_code" = '+690', "language" = 'eng' WHERE "code" = 'TK';
UPDATE "country" SET "currency" = 'USD', "calling_code" = '+670', "language" = 'por' WHERE "code" = 'TL';
UPDATE "country" SET "currency" = 'TMT', "calling_code" = '+993', "language" = 'tuk' WHERE "code" = 'TM';
UPDATE "country" SET "currency" = 'TND', "calling_code" = '+216', "language" = 'ara' WHERE "code" = 'TN';
UPDATE "country" SET "currency" = 'TOP', "calling_code" = '+676', "language" = 'eng' WHERE "code" = 'TO';
UPDATE "country" SET "currency" = 'TRY', "calling_code" = '+90', "language" = 'tur' WHERE "code" = 'TR';
UPDATE "country" SET "currency" = 'TTD', "calling_code" = '+1 868', "language" = 'eng' WHERE "code" = 'TT';
UPDATE "country" SET "currency" = 'AUD', "calling_code" = '+688', "language" = 'eng' WHERE "code" = 'TV';
UPDATE "country" SET "currency" = 'TWD', "calling_code" = '+886', "language" = 'chi' WHERE "code" = 'TW';
UPDATE "country" SET "currency" = 'TZS', "calling_code" = '+255', "language" = 'swa' WHERE "code" = 'TZ';
UPDATE "country" SET "currency" = 'UAH', "calling_code" = '+380', "language" = 'ukr' WHERE "code" = 'UA';
UPDATE "country" SET "currency" = 'UGX', "calling_code" = '+256', "language" = 'eng' WHERE "code" = 'UG';
UPDATE "country" SET "currency" = 'USD', "calling_code" = '+1', "language" = 'eng' WHERE "code" = 'UM';
UPDATE "country" SET "currency" = 'USD', "calling_code" = '+1', "language" = 'eng' WHERE "code" = 'US';
UPDATE "country" SET "currency" = 'UYU', "calling_code" = '+598', "language" = 'spa' WHERE "code" = 'UY';
UPDATE "country" SET "currency" = 'UZS', "calling_code" = '+998', "language" = 'uzb' WHERE "code" = 'UZ';
UPDATE "country" SET "currency" = 'EUR', "calling_code" = '+379', "language" = 'ita' WHERE "code" = 'VA';
UPDATE "country" SET "currency" = 'XCD', "calling_code" = '+1 784', "language" = 'eng' WHERE "code" = 'VC';
UPDATE "country" SET "currency" = 'VEF', "calling_code" = '+58', "language" = 'spa' WHERE "code" = 'VE';
UPDATE "country" SET "currency" = 'USD', "calling_code" = '+1 284', "language" = 'eng' WHERE "code" = 'VG';
UPDATE "country" SET "currency" = 'USD', "calling_code" = '+1 340', "language" = 'eng' WHERE "code" = 'VI';
UPDATE "country" SET "currency" = 'VND', "calling_code" = '+84', "language" = 'vie' WHERE "code" = 'VN';
UPDATE "country" SET "currency" = 'VUV', "calling_code" = '+678', "language" = 'bis' WHERE "code" = 'VU';
UPDATE "country" SET "currency" = 'XPF', "calling_code" = '+681', "language" = 'fre' WHERE "code" = 'WF';
UPDATE "country" SET "currency" = 'WST', "calling_code" = '+685', "language" = 'eng' WHERE "code" = 'WS';
UPDATE "country" SET "currency" = 'YER', "calling_code" = '+967', "language" = 'ara' WHERE "code" = 'YE';
UPDATE "country" SET "currency" = 'EUR', "calling_code" = '+262', "language" = 'fre' WHERE "code" = 'YT';
UPDATE "country" SET "currency" = 'ZAR', "calling_code" = '+27', "language" = 'afr' WHERE "code" = 'ZA';
UPDATE "country" SET "currency" = 'ZMW', "calling_code" = '+260', "language" = 'eng' WHERE "code" = 'ZM';
UPDATE "country" SET "currency" = 'USD', "calling_code" = '+263', "language" = 'eng' WHERE "code" = 'ZW';
