// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/m3-app/backend/ent/address"
	"github.com/m3-app/backend/ent/location"
	"github.com/m3-app/backend/ent/predicate"
)

// AddressUpdate is the builder for updating Address entities.
type AddressUpdate struct {
	config
	hooks    []Hook
	mutation *AddressMutation
}

// Where appends a list predicates to the AddressUpdate builder.
func (au *AddressUpdate) Where(ps ...predicate.Address) *AddressUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetLatitude sets the "latitude" field.
func (au *AddressUpdate) SetLatitude(f float64) *AddressUpdate {
	au.mutation.ResetLatitude()
	au.mutation.SetLatitude(f)
	return au
}

// AddLatitude adds f to the "latitude" field.
func (au *AddressUpdate) AddLatitude(f float64) *AddressUpdate {
	au.mutation.AddLatitude(f)
	return au
}

// SetLongitude sets the "longitude" field.
func (au *AddressUpdate) SetLongitude(f float64) *AddressUpdate {
	au.mutation.ResetLongitude()
	au.mutation.SetLongitude(f)
	return au
}

// AddLongitude adds f to the "longitude" field.
func (au *AddressUpdate) AddLongitude(f float64) *AddressUpdate {
	au.mutation.AddLongitude(f)
	return au
}

// SetMapsLink sets the "maps_link" field.
func (au *AddressUpdate) SetMapsLink(s string) *AddressUpdate {
	au.mutation.SetMapsLink(s)
	return au
}

// SetFullAddress sets the "full_address" field.
func (au *AddressUpdate) SetFullAddress(s string) *AddressUpdate {
	au.mutation.SetFullAddress(s)
	return au
}

// SetLocationID sets the "location" edge to the Location entity by ID.
func (au *AddressUpdate) SetLocationID(id uuid.UUID) *AddressUpdate {
	au.mutation.SetLocationID(id)
	return au
}

// SetNillableLocationID sets the "location" edge to the Location entity by ID if the given value is not nil.
func (au *AddressUpdate) SetNillableLocationID(id *uuid.UUID) *AddressUpdate {
	if id != nil {
		au = au.SetLocationID(*id)
	}
	return au
}

// SetLocation sets the "location" edge to the Location entity.
func (au *AddressUpdate) SetLocation(l *Location) *AddressUpdate {
	return au.SetLocationID(l.ID)
}

// Mutation returns the AddressMutation object of the builder.
func (au *AddressUpdate) Mutation() *AddressMutation {
	return au.mutation
}

// ClearLocation clears the "location" edge to the Location entity.
func (au *AddressUpdate) ClearLocation() *AddressUpdate {
	au.mutation.ClearLocation()
	return au
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AddressUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, AddressMutation](ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *AddressUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AddressUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AddressUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

func (au *AddressUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(address.Table, address.Columns, sqlgraph.NewFieldSpec(address.FieldID, field.TypeUUID))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.Latitude(); ok {
		_spec.SetField(address.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := au.mutation.AddedLatitude(); ok {
		_spec.AddField(address.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := au.mutation.Longitude(); ok {
		_spec.SetField(address.FieldLongitude, field.TypeFloat64, value)
	}
	if value, ok := au.mutation.AddedLongitude(); ok {
		_spec.AddField(address.FieldLongitude, field.TypeFloat64, value)
	}
	if value, ok := au.mutation.MapsLink(); ok {
		_spec.SetField(address.FieldMapsLink, field.TypeString, value)
	}
	if value, ok := au.mutation.FullAddress(); ok {
		_spec.SetField(address.FieldFullAddress, field.TypeString, value)
	}
	if au.mutation.LocationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   address.LocationTable,
			Columns: []string{address.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: location.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.LocationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   address.LocationTable,
			Columns: []string{address.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: location.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{address.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// AddressUpdateOne is the builder for updating a single Address entity.
type AddressUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AddressMutation
}

// SetLatitude sets the "latitude" field.
func (auo *AddressUpdateOne) SetLatitude(f float64) *AddressUpdateOne {
	auo.mutation.ResetLatitude()
	auo.mutation.SetLatitude(f)
	return auo
}

// AddLatitude adds f to the "latitude" field.
func (auo *AddressUpdateOne) AddLatitude(f float64) *AddressUpdateOne {
	auo.mutation.AddLatitude(f)
	return auo
}

// SetLongitude sets the "longitude" field.
func (auo *AddressUpdateOne) SetLongitude(f float64) *AddressUpdateOne {
	auo.mutation.ResetLongitude()
	auo.mutation.SetLongitude(f)
	return auo
}

// AddLongitude adds f to the "longitude" field.
func (auo *AddressUpdateOne) AddLongitude(f float64) *AddressUpdateOne {
	auo.mutation.AddLongitude(f)
	return auo
}

// SetMapsLink sets the "maps_link" field.
func (auo *AddressUpdateOne) SetMapsLink(s string) *AddressUpdateOne {
	auo.mutation.SetMapsLink(s)
	return auo
}

// SetFullAddress sets the "full_address" field.
func (auo *AddressUpdateOne) SetFullAddress(s string) *AddressUpdateOne {
	auo.mutation.SetFullAddress(s)
	return auo
}

// SetLocationID sets the "location" edge to the Location entity by ID.
func (auo *AddressUpdateOne) SetLocationID(id uuid.UUID) *AddressUpdateOne {
	auo.mutation.SetLocationID(id)
	return auo
}

// SetNillableLocationID sets the "location" edge to the Location entity by ID if the given value is not nil.
func (auo *AddressUpdateOne) SetNillableLocationID(id *uuid.UUID) *AddressUpdateOne {
	if id != nil {
		auo = auo.SetLocationID(*id)
	}
	return auo
}

// SetLocation sets the "location" edge to the Location entity.
func (auo *AddressUpdateOne) SetLocation(l *Location) *AddressUpdateOne {
	return auo.SetLocationID(l.ID)
}

// Mutation returns the AddressMutation object of the builder.
func (auo *AddressUpdateOne) Mutation() *AddressMutation {
	return auo.mutation
}

// ClearLocation clears the "location" edge to the Location entity.
func (auo *AddressUpdateOne) ClearLocation() *AddressUpdateOne {
	auo.mutation.ClearLocation()
	return auo
}

// Where appends a list predicates to the AddressUpdate builder.
func (auo *AddressUpdateOne) Where(ps ...predicate.Address) *AddressUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AddressUpdateOne) Select(field string, fields ...string) *AddressUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Address entity.
func (auo *AddressUpdateOne) Save(ctx context.Context) (*Address, error) {
	return withHooks[*Address, AddressMutation](ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AddressUpdateOne) SaveX(ctx context.Context) *Address {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AddressUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AddressUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (auo *AddressUpdateOne) sqlSave(ctx context.Context) (_node *Address, err error) {
	_spec := sqlgraph.NewUpdateSpec(address.Table, address.Columns, sqlgraph.NewFieldSpec(address.FieldID, field.TypeUUID))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Address.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, address.FieldID)
		for _, f := range fields {
			if !address.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != address.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.Latitude(); ok {
		_spec.SetField(address.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := auo.mutation.AddedLatitude(); ok {
		_spec.AddField(address.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := auo.mutation.Longitude(); ok {
		_spec.SetField(address.FieldLongitude, field.TypeFloat64, value)
	}
	if value, ok := auo.mutation.AddedLongitude(); ok {
		_spec.AddField(address.FieldLongitude, field.TypeFloat64, value)
	}
	if value, ok := auo.mutation.MapsLink(); ok {
		_spec.SetField(address.FieldMapsLink, field.TypeString, value)
	}
	if value, ok := auo.mutation.FullAddress(); ok {
		_spec.SetField(address.FieldFullAddress, field.TypeString, value)
	}
	if auo.mutation.LocationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   address.LocationTable,
			Columns: []string{address.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: location.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.LocationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   address.LocationTable,
			Columns: []string{address.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: location.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Address{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{address.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
