// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/m3-app/backend/ent/address"
	"github.com/m3-app/backend/ent/location"
	"github.com/m3-app/backend/ent/owner"
	"github.com/m3-app/backend/ent/predicate"
	"github.com/m3-app/backend/ent/review"
)

// LocationUpdate is the builder for updating Location entities.
type LocationUpdate struct {
	config
	hooks    []Hook
	mutation *LocationMutation
}

// Where appends a list predicates to the LocationUpdate builder.
func (lu *LocationUpdate) Where(ps ...predicate.Location) *LocationUpdate {
	lu.mutation.Where(ps...)
	return lu
}

// SetName sets the "name" field.
func (lu *LocationUpdate) SetName(s string) *LocationUpdate {
	lu.mutation.SetName(s)
	return lu
}

// SetType sets the "type" field.
func (lu *LocationUpdate) SetType(s string) *LocationUpdate {
	lu.mutation.SetType(s)
	return lu
}

// AddAddresIDs adds the "address" edge to the Address entity by IDs.
func (lu *LocationUpdate) AddAddresIDs(ids ...uuid.UUID) *LocationUpdate {
	lu.mutation.AddAddresIDs(ids...)
	return lu
}

// AddAddress adds the "address" edges to the Address entity.
func (lu *LocationUpdate) AddAddress(a ...*Address) *LocationUpdate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return lu.AddAddresIDs(ids...)
}

// AddReviewIDs adds the "reviews" edge to the Review entity by IDs.
func (lu *LocationUpdate) AddReviewIDs(ids ...uuid.UUID) *LocationUpdate {
	lu.mutation.AddReviewIDs(ids...)
	return lu
}

// AddReviews adds the "reviews" edges to the Review entity.
func (lu *LocationUpdate) AddReviews(r ...*Review) *LocationUpdate {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return lu.AddReviewIDs(ids...)
}

// SetOwnerID sets the "owner" edge to the Owner entity by ID.
func (lu *LocationUpdate) SetOwnerID(id uuid.UUID) *LocationUpdate {
	lu.mutation.SetOwnerID(id)
	return lu
}

// SetNillableOwnerID sets the "owner" edge to the Owner entity by ID if the given value is not nil.
func (lu *LocationUpdate) SetNillableOwnerID(id *uuid.UUID) *LocationUpdate {
	if id != nil {
		lu = lu.SetOwnerID(*id)
	}
	return lu
}

// SetOwner sets the "owner" edge to the Owner entity.
func (lu *LocationUpdate) SetOwner(o *Owner) *LocationUpdate {
	return lu.SetOwnerID(o.ID)
}

// Mutation returns the LocationMutation object of the builder.
func (lu *LocationUpdate) Mutation() *LocationMutation {
	return lu.mutation
}

// ClearAddress clears all "address" edges to the Address entity.
func (lu *LocationUpdate) ClearAddress() *LocationUpdate {
	lu.mutation.ClearAddress()
	return lu
}

// RemoveAddresIDs removes the "address" edge to Address entities by IDs.
func (lu *LocationUpdate) RemoveAddresIDs(ids ...uuid.UUID) *LocationUpdate {
	lu.mutation.RemoveAddresIDs(ids...)
	return lu
}

// RemoveAddress removes "address" edges to Address entities.
func (lu *LocationUpdate) RemoveAddress(a ...*Address) *LocationUpdate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return lu.RemoveAddresIDs(ids...)
}

// ClearReviews clears all "reviews" edges to the Review entity.
func (lu *LocationUpdate) ClearReviews() *LocationUpdate {
	lu.mutation.ClearReviews()
	return lu
}

// RemoveReviewIDs removes the "reviews" edge to Review entities by IDs.
func (lu *LocationUpdate) RemoveReviewIDs(ids ...uuid.UUID) *LocationUpdate {
	lu.mutation.RemoveReviewIDs(ids...)
	return lu
}

// RemoveReviews removes "reviews" edges to Review entities.
func (lu *LocationUpdate) RemoveReviews(r ...*Review) *LocationUpdate {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return lu.RemoveReviewIDs(ids...)
}

// ClearOwner clears the "owner" edge to the Owner entity.
func (lu *LocationUpdate) ClearOwner() *LocationUpdate {
	lu.mutation.ClearOwner()
	return lu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (lu *LocationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, LocationMutation](ctx, lu.sqlSave, lu.mutation, lu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (lu *LocationUpdate) SaveX(ctx context.Context) int {
	affected, err := lu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (lu *LocationUpdate) Exec(ctx context.Context) error {
	_, err := lu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lu *LocationUpdate) ExecX(ctx context.Context) {
	if err := lu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (lu *LocationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(location.Table, location.Columns, sqlgraph.NewFieldSpec(location.FieldID, field.TypeUUID))
	if ps := lu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lu.mutation.Name(); ok {
		_spec.SetField(location.FieldName, field.TypeString, value)
	}
	if value, ok := lu.mutation.GetType(); ok {
		_spec.SetField(location.FieldType, field.TypeString, value)
	}
	if lu.mutation.AddressCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.AddressTable,
			Columns: []string{location.AddressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: address.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lu.mutation.RemovedAddressIDs(); len(nodes) > 0 && !lu.mutation.AddressCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.AddressTable,
			Columns: []string{location.AddressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: address.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lu.mutation.AddressIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.AddressTable,
			Columns: []string{location.AddressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: address.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if lu.mutation.ReviewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   location.ReviewsTable,
			Columns: location.ReviewsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: review.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lu.mutation.RemovedReviewsIDs(); len(nodes) > 0 && !lu.mutation.ReviewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   location.ReviewsTable,
			Columns: location.ReviewsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: review.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lu.mutation.ReviewsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   location.ReviewsTable,
			Columns: location.ReviewsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: review.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if lu.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   location.OwnerTable,
			Columns: []string{location.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: owner.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lu.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   location.OwnerTable,
			Columns: []string{location.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: owner.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, lu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{location.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	lu.mutation.done = true
	return n, nil
}

// LocationUpdateOne is the builder for updating a single Location entity.
type LocationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LocationMutation
}

// SetName sets the "name" field.
func (luo *LocationUpdateOne) SetName(s string) *LocationUpdateOne {
	luo.mutation.SetName(s)
	return luo
}

// SetType sets the "type" field.
func (luo *LocationUpdateOne) SetType(s string) *LocationUpdateOne {
	luo.mutation.SetType(s)
	return luo
}

// AddAddresIDs adds the "address" edge to the Address entity by IDs.
func (luo *LocationUpdateOne) AddAddresIDs(ids ...uuid.UUID) *LocationUpdateOne {
	luo.mutation.AddAddresIDs(ids...)
	return luo
}

// AddAddress adds the "address" edges to the Address entity.
func (luo *LocationUpdateOne) AddAddress(a ...*Address) *LocationUpdateOne {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return luo.AddAddresIDs(ids...)
}

// AddReviewIDs adds the "reviews" edge to the Review entity by IDs.
func (luo *LocationUpdateOne) AddReviewIDs(ids ...uuid.UUID) *LocationUpdateOne {
	luo.mutation.AddReviewIDs(ids...)
	return luo
}

// AddReviews adds the "reviews" edges to the Review entity.
func (luo *LocationUpdateOne) AddReviews(r ...*Review) *LocationUpdateOne {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return luo.AddReviewIDs(ids...)
}

// SetOwnerID sets the "owner" edge to the Owner entity by ID.
func (luo *LocationUpdateOne) SetOwnerID(id uuid.UUID) *LocationUpdateOne {
	luo.mutation.SetOwnerID(id)
	return luo
}

// SetNillableOwnerID sets the "owner" edge to the Owner entity by ID if the given value is not nil.
func (luo *LocationUpdateOne) SetNillableOwnerID(id *uuid.UUID) *LocationUpdateOne {
	if id != nil {
		luo = luo.SetOwnerID(*id)
	}
	return luo
}

// SetOwner sets the "owner" edge to the Owner entity.
func (luo *LocationUpdateOne) SetOwner(o *Owner) *LocationUpdateOne {
	return luo.SetOwnerID(o.ID)
}

// Mutation returns the LocationMutation object of the builder.
func (luo *LocationUpdateOne) Mutation() *LocationMutation {
	return luo.mutation
}

// ClearAddress clears all "address" edges to the Address entity.
func (luo *LocationUpdateOne) ClearAddress() *LocationUpdateOne {
	luo.mutation.ClearAddress()
	return luo
}

// RemoveAddresIDs removes the "address" edge to Address entities by IDs.
func (luo *LocationUpdateOne) RemoveAddresIDs(ids ...uuid.UUID) *LocationUpdateOne {
	luo.mutation.RemoveAddresIDs(ids...)
	return luo
}

// RemoveAddress removes "address" edges to Address entities.
func (luo *LocationUpdateOne) RemoveAddress(a ...*Address) *LocationUpdateOne {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return luo.RemoveAddresIDs(ids...)
}

// ClearReviews clears all "reviews" edges to the Review entity.
func (luo *LocationUpdateOne) ClearReviews() *LocationUpdateOne {
	luo.mutation.ClearReviews()
	return luo
}

// RemoveReviewIDs removes the "reviews" edge to Review entities by IDs.
func (luo *LocationUpdateOne) RemoveReviewIDs(ids ...uuid.UUID) *LocationUpdateOne {
	luo.mutation.RemoveReviewIDs(ids...)
	return luo
}

// RemoveReviews removes "reviews" edges to Review entities.
func (luo *LocationUpdateOne) RemoveReviews(r ...*Review) *LocationUpdateOne {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return luo.RemoveReviewIDs(ids...)
}

// ClearOwner clears the "owner" edge to the Owner entity.
func (luo *LocationUpdateOne) ClearOwner() *LocationUpdateOne {
	luo.mutation.ClearOwner()
	return luo
}

// Where appends a list predicates to the LocationUpdate builder.
func (luo *LocationUpdateOne) Where(ps ...predicate.Location) *LocationUpdateOne {
	luo.mutation.Where(ps...)
	return luo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (luo *LocationUpdateOne) Select(field string, fields ...string) *LocationUpdateOne {
	luo.fields = append([]string{field}, fields...)
	return luo
}

// Save executes the query and returns the updated Location entity.
func (luo *LocationUpdateOne) Save(ctx context.Context) (*Location, error) {
	return withHooks[*Location, LocationMutation](ctx, luo.sqlSave, luo.mutation, luo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (luo *LocationUpdateOne) SaveX(ctx context.Context) *Location {
	node, err := luo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (luo *LocationUpdateOne) Exec(ctx context.Context) error {
	_, err := luo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (luo *LocationUpdateOne) ExecX(ctx context.Context) {
	if err := luo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (luo *LocationUpdateOne) sqlSave(ctx context.Context) (_node *Location, err error) {
	_spec := sqlgraph.NewUpdateSpec(location.Table, location.Columns, sqlgraph.NewFieldSpec(location.FieldID, field.TypeUUID))
	id, ok := luo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Location.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := luo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, location.FieldID)
		for _, f := range fields {
			if !location.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != location.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := luo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := luo.mutation.Name(); ok {
		_spec.SetField(location.FieldName, field.TypeString, value)
	}
	if value, ok := luo.mutation.GetType(); ok {
		_spec.SetField(location.FieldType, field.TypeString, value)
	}
	if luo.mutation.AddressCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.AddressTable,
			Columns: []string{location.AddressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: address.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := luo.mutation.RemovedAddressIDs(); len(nodes) > 0 && !luo.mutation.AddressCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.AddressTable,
			Columns: []string{location.AddressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: address.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := luo.mutation.AddressIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   location.AddressTable,
			Columns: []string{location.AddressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: address.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if luo.mutation.ReviewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   location.ReviewsTable,
			Columns: location.ReviewsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: review.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := luo.mutation.RemovedReviewsIDs(); len(nodes) > 0 && !luo.mutation.ReviewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   location.ReviewsTable,
			Columns: location.ReviewsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: review.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := luo.mutation.ReviewsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   location.ReviewsTable,
			Columns: location.ReviewsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: review.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if luo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   location.OwnerTable,
			Columns: []string{location.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: owner.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := luo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   location.OwnerTable,
			Columns: []string{location.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: owner.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Location{config: luo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, luo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{location.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	luo.mutation.done = true
	return _node, nil
}
