package gresolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	"fmt"

	"github.com/stadio-app/stadio-backend/graph"
	"github.com/stadio-app/stadio-backend/graph/gmodel"
)

// CreateEvent is the resolver for the createEvent field.
func (r *mutationResolver) CreateEvent(ctx context.Context, input gmodel.CreateEvent) (*gmodel.EventShallow, error) {
	event, err := r.Service.CreateEvent(ctx, r.Service.GetAuthUserFromContext(ctx), input)
	return &event, err
}

// AllEvents is the resolver for the allEvents field.
func (r *queryResolver) AllEvents(ctx context.Context, filter gmodel.AllEventsFilter) ([]*gmodel.Event, error) {
	if err := r.Service.StructValidator.StructCtx(ctx, filter); err != nil {
		return nil, err
	}

	events, err := r.Service.FindAllEvents(ctx, filter)
	if err != nil {
		return nil, err
	}
	event_ptrs := make([]*gmodel.Event, len(events))
	for i := range events {
		event_ptrs[i] = &events[i]
	}
	return event_ptrs, nil
}

// EventDetails is the resolver for the eventDetails field.
func (r *queryResolver) EventDetails(ctx context.Context, eventID int64) (*gmodel.Event, error) {
	panic(fmt.Errorf("not implemented: EventDetails - eventDetails"))
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
