// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Address is the predicate function for address builders.
type Address func(*sql.Selector)

// Location is the predicate function for location builders.
type Location func(*sql.Selector)

// Owner is the predicate function for owner builders.
type Owner func(*sql.Selector)

// Review is the predicate function for review builders.
type Review func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
